# Working with NumPy

---

**NumPy** is Python's array library, which provides a "language" to interact with vector valued data. The first thing to understand is the variety of ways in which to access arrays.

In [18]:
from numpy import *
import numpy as np

a = np.random.randn(40)

# traditional 
print "traditional"
print a[0]
print a[0:5] #starts from zero.

print a[0:20:10]

#reverse
print "reverse"
print a[30::-10]

print a[::-10]

# logical
print "Logical"
print a[a>0]

b = np.random.randn(25)


print a[(b-0.5)<0]
print a[b<0]

traditional
-0.623704829491
[-0.62370483 -0.27627642  0.4731122   0.0576616   1.69698205]
[-0.62370483  0.61109131]
reverse
[ 0.61631724 -0.61180654  0.61109131 -0.62370483]
[ 0.08145014 -0.54503414  0.530185   -1.14183178]
Logical
[ 0.4731122   0.0576616   1.69698205  0.64768757  0.61109131  0.79147275
  0.73767765  1.11018349  0.34026107  0.530185    0.913556    0.22588601
  0.61631724  1.12722588  0.13512307  0.66123097  0.9003131   0.08145014]
[-0.27627642  0.4731122  -0.69652959 -1.25744016 -1.14183178 -1.78244911
  0.79147275  0.73767765 -1.0497299  -1.91792491  1.11018349  0.34026107
  0.530185   -0.61180654 -0.7642491 ]
[ 0.4731122  -1.25744016 -1.78244911  0.79147275  0.73767765 -1.0497299
 -1.91792491  0.34026107  0.530185   -0.61180654 -0.7642491 ]


Arrays can be "broadcast" to multiply with higher dimensional arrays.

In [26]:


a = a.reshape((10,-1))

c = np.random.randn(10)

d = a*c[:,newaxis] #Note multiplication is elementwise, not matrix multiplication
print d.shape

(10, 4)
